---
apiVersion: v1
kind: Secret
metadata:
  name: nifcloud-cloud-controller-manager-secret
  namespace: kube-system
stringData:
  access_key_id: ""
  secret_access_key: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: nifcloud-cloud-controller-manager
  name: nifcloud-cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: nifcloud-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: nifcloud-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
      - name: nifcloud-cloud-controller-manager
        image: aokumasan/nifcloud-cloud-controller-manager:latest
        command:
        - /bin/cloud-controller-manager
        - --cloud-provider=nifcloud
        - --leader-elect=true
        - --use-service-account-credentials
        env:
        - name: NIFCLOUD_REGION
          value: jp-east-1
        - name: NIFCLOUD_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: nifcloud-cloud-controller-manager-secret
              key: access_key_id
        - name: NIFCLOUD_SECRET_ACCESS_KEY
        valueFrom:
            secretKeyRef:
              name: nifcloud-cloud-controller-manager-secret
              key: secret_access_key
      hostNetwork: true
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
